version: 2.1

jobs:
  build:
    machine: true
    steps:
    - run:
        name: Retrive logs
        command: journalctl -f --no-pager
        background: true
    - run: sudo ip link
    - run: sudo ip link show tun0
